name: Deploy to GitHub Pages with gh-pages

on:
  push:
    branches:
      - main # Cambia si tu branch principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código desde GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Cambia si necesitas otra versión de Node.js

      # 3. Instalar Dependencias
      - name: Install Dependencies
        run: npm install

      # 4. Compilar TailwindCSS
      - name: Build TailwindCSS
        run: npm run build

      # 5. Desplegar usando gh-pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
